-- M1: identity, tenancy and audit tables. The first half is generated by drizzle-kit from
-- src/schema; the second half (after the banner) is hand-written: request context,
-- row-level security, grants, SECURITY DEFINER functions and triggers.
-- See ARCHITECTURE.md section 5, ADR-0002, ADR-0015 and ADR-0016.

CREATE TYPE "public"."auth_token_purpose" AS ENUM('verify_email', 'password_reset', 'magic_link');--> statement-breakpoint
CREATE TYPE "public"."membership_role" AS ENUM('owner', 'admin', 'approver', 'reviewer', 'viewer');--> statement-breakpoint
CREATE TABLE "auth_tokens" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"user_id" uuid NOT NULL,
	"purpose" "auth_token_purpose" NOT NULL,
	"token_hash" "bytea" NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "auth_tokens_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"user_id" uuid NOT NULL,
	"token_hash" "bytea" NOT NULL,
	"active_org_id" uuid,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "sessions_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "user_credentials" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"password_hash" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"email" "citext" NOT NULL,
	"name" text NOT NULL,
	"email_verified_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "invites" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"org_id" uuid NOT NULL,
	"email" "citext" NOT NULL,
	"role" "membership_role" NOT NULL,
	"token_hash" "bytea" NOT NULL,
	"invited_by" uuid,
	"expires_at" timestamp with time zone NOT NULL,
	"accepted_at" timestamp with time zone,
	"accepted_by" uuid,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invites_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
CREATE TABLE "memberships" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"org_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"role" "membership_role" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "memberships_org_user_uq" UNIQUE("org_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"plan" text DEFAULT 'trial' NOT NULL,
	"stripe_customer_id" text,
	"settings" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organizations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT uuid_generate_v7() NOT NULL,
	"org_id" uuid NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text,
	"before" jsonb,
	"after" jsonb,
	"ip" "inet",
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "auth_tokens" ADD CONSTRAINT "auth_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_credentials" ADD CONSTRAINT "user_credentials_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_invited_by_users_id_fk" FOREIGN KEY ("invited_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invites" ADD CONSTRAINT "invites_accepted_by_users_id_fk" FOREIGN KEY ("accepted_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "auth_tokens_user_purpose_idx" ON "auth_tokens" USING btree ("user_id","purpose");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "invites_open_email_uq" ON "invites" USING btree ("org_id","email") WHERE accepted_at IS NULL AND revoked_at IS NULL;--> statement-breakpoint
CREATE INDEX "memberships_user_id_idx" ON "memberships" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "audit_log_org_created_idx" ON "audit_log" USING btree ("org_id","created_at" DESC NULLS LAST);
--> statement-breakpoint

-- =========================================================================================
-- Hand-written from here on (not generated by drizzle-kit).
-- =========================================================================================

-- Request context. packages/db sets both with set_config(..., true), so they last for one
-- transaction. After commit a pooled connection reports '' rather than NULL, hence NULLIF:
-- an unset context matches no rows instead of raising a cast error.
CREATE FUNCTION app_org_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE
AS $$ SELECT NULLIF(pg_catalog.current_setting('app.org_id', true), '')::uuid $$;
--> statement-breakpoint
CREATE FUNCTION app_user_id() RETURNS uuid
LANGUAGE sql STABLE PARALLEL SAFE
AS $$ SELECT NULLIF(pg_catalog.current_setting('app.user_id', true), '')::uuid $$;
--> statement-breakpoint

-- updated_at is maintained here so application code cannot forget it.
CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END
$$;
--> statement-breakpoint
CREATE TRIGGER organizations_set_updated_at BEFORE UPDATE ON organizations
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--> statement-breakpoint
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--> statement-breakpoint
CREATE TRIGGER user_credentials_set_updated_at BEFORE UPDATE ON user_credentials
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--> statement-breakpoint
CREATE TRIGGER memberships_set_updated_at BEFORE UPDATE ON memberships
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
--> statement-breakpoint

-- Constraints Drizzle does not express.
ALTER TABLE organizations ADD CONSTRAINT organizations_name_length
  CHECK (char_length(name) BETWEEN 1 AND 200);
--> statement-breakpoint
ALTER TABLE users ADD CONSTRAINT users_name_length CHECK (char_length(name) BETWEEN 1 AND 200);
--> statement-breakpoint
ALTER TABLE users ADD CONSTRAINT users_email_length CHECK (char_length(email) BETWEEN 3 AND 320);
--> statement-breakpoint
ALTER TABLE invites ADD CONSTRAINT invites_email_length CHECK (char_length(email) BETWEEN 3 AND 320);
--> statement-breakpoint
-- A session's active org must be one of its user's memberships. Removing the membership
-- clears the active org (PG15+ column list) instead of deleting the session.
ALTER TABLE sessions ADD CONSTRAINT sessions_active_membership_fk
  FOREIGN KEY (active_org_id, user_id) REFERENCES memberships (org_id, user_id)
  ON DELETE SET NULL (active_org_id);
--> statement-breakpoint

-- -----------------------------------------------------------------------------------------
-- Row-level security. Every table in this schema has it enabled; the enumeration test in
-- packages/db/src/rls.int.test.ts fails otherwise. Not FORCEd: the owner role runs
-- migrations and owns the SECURITY DEFINER functions below (ADR-0015).
-- -----------------------------------------------------------------------------------------
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE invites ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE user_credentials ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE auth_tokens ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint

-- Tenant tables: the current org only.
CREATE POLICY memberships_tenant ON memberships FOR ALL
  USING (org_id = app_org_id()) WITH CHECK (org_id = app_org_id());
--> statement-breakpoint
-- A user may also read their own memberships in other orgs (org switcher). Read-only;
-- listed as an allowed exception in the enumeration test (resolves C7).
CREATE POLICY memberships_own_select ON memberships FOR SELECT
  USING (user_id = app_user_id());
--> statement-breakpoint
CREATE POLICY invites_tenant ON invites FOR ALL
  USING (org_id = app_org_id()) WITH CHECK (org_id = app_org_id());
--> statement-breakpoint
CREATE POLICY audit_log_select ON audit_log FOR SELECT
  USING (org_id = app_org_id());
--> statement-breakpoint
CREATE POLICY audit_log_insert ON audit_log FOR INSERT
  WITH CHECK (org_id = app_org_id());
--> statement-breakpoint

-- organizations: the current org, plus orgs the current user belongs to (names for the
-- switcher). Updates only in the current org. Creation goes through create_organization().
CREATE POLICY organizations_select ON organizations FOR SELECT
  USING (
    id = app_org_id()
    OR EXISTS (
      SELECT 1 FROM memberships m
      WHERE m.org_id = organizations.id AND m.user_id = app_user_id()
    )
  );
--> statement-breakpoint
CREATE POLICY organizations_update ON organizations FOR UPDATE
  USING (id = app_org_id()) WITH CHECK (id = app_org_id());
--> statement-breakpoint

-- users: yourself, and co-members of the current org (member lists).
CREATE POLICY users_select ON users FOR SELECT
  USING (
    id = app_user_id()
    OR EXISTS (
      SELECT 1 FROM memberships m
      WHERE m.user_id = users.id AND m.org_id = app_org_id()
    )
  );
--> statement-breakpoint
CREATE POLICY users_update_self ON users FOR UPDATE
  USING (id = app_user_id()) WITH CHECK (id = app_user_id());
--> statement-breakpoint
CREATE POLICY user_credentials_own ON user_credentials FOR ALL
  USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id());
--> statement-breakpoint
CREATE POLICY sessions_own ON sessions FOR ALL
  USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id());
--> statement-breakpoint
CREATE POLICY auth_tokens_own ON auth_tokens FOR ALL
  USING (user_id = app_user_id()) WITH CHECK (user_id = app_user_id());
--> statement-breakpoint

-- -----------------------------------------------------------------------------------------
-- Privileges. The baseline grants ig_app SELECT/INSERT/UPDATE/DELETE on new tables (never
-- TRUNCATE, which RLS does not govern); narrow them where the app must not write.
-- -----------------------------------------------------------------------------------------
REVOKE INSERT, DELETE ON organizations FROM ig_app;
--> statement-breakpoint
REVOKE INSERT, UPDATE, DELETE ON users FROM ig_app;
--> statement-breakpoint
GRANT UPDATE (name, email_verified_at) ON users TO ig_app;
--> statement-breakpoint
REVOKE INSERT, DELETE ON user_credentials FROM ig_app;
--> statement-breakpoint
REVOKE UPDATE, DELETE ON auth_tokens FROM ig_app;
--> statement-breakpoint
REVOKE UPDATE, DELETE ON audit_log FROM ig_app;
--> statement-breakpoint

-- -----------------------------------------------------------------------------------------
-- SECURITY DEFINER functions: the only reviewed paths that act without a user or org
-- context. They run as ig_owner (which RLS does not bind), take hashed tokens rather than
-- secrets, and return the minimum. pg_temp is last on the search_path so it cannot shadow.
-- -----------------------------------------------------------------------------------------

-- Login, magic link, password reset and signup need a user by email before any context.
CREATE FUNCTION auth_find_user_by_email(p_email citext)
RETURNS TABLE (
  id uuid, email citext, name text, email_verified_at timestamptz, password_hash text
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
  SELECT u.id, u.email, u.name, u.email_verified_at, c.password_hash
  FROM users u
  LEFT JOIN user_credentials c ON c.user_id = u.id
  WHERE u.email = p_email
$$;
--> statement-breakpoint

-- Signup. Always creates an unverified user; a duplicate email raises unique_violation.
CREATE FUNCTION auth_register_user(p_email citext, p_name text, p_password_hash text)
RETURNS uuid
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_user uuid;
BEGIN
  INSERT INTO users (email, name) VALUES (p_email, p_name) RETURNING users.id INTO v_user;
  INSERT INTO user_credentials (user_id, password_hash) VALUES (v_user, p_password_hash);
  RETURN v_user;
END
$$;
--> statement-breakpoint

-- Every authenticated request: a live session by token hash, with its user and role in the
-- active org.
CREATE FUNCTION auth_session_lookup(p_token_hash bytea)
RETURNS TABLE (
  session_id uuid, user_id uuid, expires_at timestamptz, active_org_id uuid,
  role membership_role, email citext, name text, email_verified_at timestamptz
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
  SELECT s.id, s.user_id, s.expires_at, s.active_org_id,
         m.role, u.email, u.name, u.email_verified_at
  FROM sessions s
  JOIN users u ON u.id = s.user_id
  LEFT JOIN memberships m ON m.org_id = s.active_org_id AND m.user_id = s.user_id
  WHERE s.token_hash = p_token_hash AND s.expires_at > now()
$$;
--> statement-breakpoint

-- Email links. Atomically marks a live token used and returns its user, or NULL. Using one
-- token retires the user's other open tokens of that purpose. Every purpose proves control
-- of the mailbox, so the email counts as verified.
CREATE FUNCTION auth_consume_token(p_token_hash bytea, p_purpose auth_token_purpose)
RETURNS uuid
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_user uuid;
BEGIN
  UPDATE auth_tokens t SET used_at = now()
  WHERE t.token_hash = p_token_hash
    AND t.purpose = p_purpose
    AND t.used_at IS NULL
    AND t.expires_at > now()
  RETURNING t.user_id INTO v_user;

  IF v_user IS NULL THEN
    RETURN NULL;
  END IF;

  UPDATE auth_tokens t SET used_at = now()
  WHERE t.user_id = v_user AND t.purpose = p_purpose AND t.used_at IS NULL;

  UPDATE users u SET email_verified_at = now()
  WHERE u.id = v_user AND u.email_verified_at IS NULL;

  RETURN v_user;
END
$$;
--> statement-breakpoint

-- Invite links are opened before the invitee has any context in the org.
CREATE FUNCTION invite_lookup(p_token_hash bytea)
RETURNS TABLE (
  invite_id uuid, org_id uuid, org_name text, email citext, role membership_role,
  expires_at timestamptz, accepted_at timestamptz, revoked_at timestamptz
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
  SELECT i.id, i.org_id, o.name, i.email, i.role, i.expires_at, i.accepted_at, i.revoked_at
  FROM invites i
  JOIN organizations o ON o.id = i.org_id
  WHERE i.token_hash = p_token_hash
$$;
--> statement-breakpoint

-- Creates an org and makes the current user (app.user_id) its owner, atomically, so no org
-- ever exists without an owner. The slug gets a random suffix; collisions are retried.
CREATE FUNCTION create_organization(p_name text, p_slug_base text)
RETURNS uuid
LANGUAGE plpgsql VOLATILE SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_user uuid := app_user_id();
  v_org uuid;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'create_organization requires a user context'
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  IF p_slug_base IS NULL OR p_slug_base !~ '^[a-z0-9]+(-[a-z0-9]+)*$'
     OR char_length(p_slug_base) > 40 THEN
    RAISE EXCEPTION 'invalid slug base' USING ERRCODE = 'check_violation';
  END IF;

  FOR attempt IN 1..5 LOOP
    BEGIN
      INSERT INTO organizations (name, slug)
      VALUES (p_name, p_slug_base || '-' || encode(gen_random_bytes(3), 'hex'))
      RETURNING organizations.id INTO v_org;
      EXIT;
    EXCEPTION WHEN unique_violation THEN
      IF attempt = 5 THEN
        RAISE;
      END IF;
    END;
  END LOOP;

  INSERT INTO memberships (org_id, user_id, role) VALUES (v_org, v_user, 'owner');
  RETURN v_org;
END
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION
  auth_find_user_by_email(citext),
  auth_register_user(citext, text, text),
  auth_session_lookup(bytea),
  auth_consume_token(bytea, auth_token_purpose),
  invite_lookup(bytea),
  create_organization(text, text)
FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION
  auth_find_user_by_email(citext),
  auth_register_user(citext, text, text),
  auth_session_lookup(bytea),
  auth_consume_token(bytea, auth_token_purpose),
  invite_lookup(bytea),
  create_organization(text, text)
TO ig_app;
--> statement-breakpoint

-- -----------------------------------------------------------------------------------------
-- audit_log is append-only for every role, including the owner (FR-ADM-1, ADR-0016).
-- -----------------------------------------------------------------------------------------
CREATE FUNCTION audit_log_reject_change() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only: % is not allowed', TG_OP
    USING ERRCODE = 'IG001';
END
$$;
--> statement-breakpoint
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_reject_change();
--> statement-breakpoint
CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log
  FOR EACH STATEMENT EXECUTE FUNCTION audit_log_reject_change();
