import { sql } from 'drizzle-orm';
import { customType, timestamp, uuid } from 'drizzle-orm/pg-core';

/** Case-insensitive text (citext extension); used for email addresses. */
export const citext = customType<{ data: string }>({
  dataType: () => 'citext',
});

export const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType: () => 'bytea',
});

/** UUID v7 primary key generated by the database (ADR-0014). */
export const primaryId = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuid_generate_v7()`);

export const createdAt = () =>
  timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

/** Maintained by the `set_updated_at` trigger, not by application code. */
export const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
